run_lox:
	go run cmd/lox/main.go

gen_ast:
	go run cmd/tool/main.go generate_ast

print_ast:
	go run cmd/tool/main.go print_ast

# Expressions
		# Arithmetic: 1 + 2 * 3 - 4 / 2;
		# Comparisons: 5 > 3; or "hello" == "world";
		# Boolean logic: !(5 > 3); or true == false;
		# Complex nesting: ((1 + 2) * 3) - (4 / 2);
		# Mixed operations: 5 + 3 > 2 * 4;
		# Unary chains: --5; or !!!true;
